In [112]:
import pandas as pd
import pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.externals import joblib
from sklearn.feature_selection import SelectKBest #feature selection best features
from sklearn.feature_selection import chi2 # clase chi-cuadrado 
import numpy as np

In [8]:
df = pd.read_csv('/data/UMG/ProDeGree/Grad I/ML/Youtube01-Psy.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 5 columns):
COMMENT_ID    350 non-null object
AUTHOR        350 non-null object
DATE          350 non-null object
CONTENT       350 non-null object
CLASS         350 non-null int64
dtypes: int64(1), object(4)
memory usage: 13.8+ KB


In [41]:
df.head()  # head muestra solo las primeras 5 lineas del dataset

COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   

   CLASS  
0      1  
1      1  
2      1  
3      1  
4      1

In [10]:
df.count()


COMMENT_ID    350
AUTHOR        350
DATE          350
CONTENT       350
CLASS         350
dtype: int64

In [39]:
df_data = df[['CONTENT', 'CLASS']]
#df_data

## Usando  selectKBest 

In [116]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

#codificar la columna content de categorica a numerica con dicVectroizer
from sklearn.feature_extraction import DictVectorizer
X_dict = X.to_dict(orient='records') # conviertiendo de dataFrame en diccionario

#print(X_dict)
X_DV = DictVectorizer(sparse=False)

X_encoded = X_DV.fit_transform(X_dict)

support = SelectKBest(score_func=chi2, k=10)
fit = support.fit(X_encoded, y)

features = fit.transform(X_encoded)
np.set_printoptions(precision=3) 

print(features)
#Summarize selected features 


#punteo_df = pd.DataFrame(fit.scores_)
#columna_df = pd.DataFrame(X.columns)

#punteo_features = pd.concat([columna_df, punteo_df], axis= 1)
#punteo_features.columns = ['variable', 'punteo']

#punteo_features
#print(punteo_features.nlargest(10, 'punteo'))

#X_DV.restrict(support.get_support())

#DictVectorizer(dtype=..., separator='=', sort=True, sparse=True)
#fit.scores_

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


## Usando  Feature importance (extra Tree classifier)

In [103]:
import seaborn as sns
data = df.to_dict(orient='records')
#get correlations of each features in dataset
corrmat = data.corr()
top_corr_features = corrmat.index
plt.figure(figsize=(20,20))
#plot heat map
g=sns.heatmap(data[top_corr_features].corr(),annot=True,cmap="RdYlGn")

AttributeError: 'list' object has no attribute 'corr'

In [104]:
X_dict = pd.get_dummies(X, prefix_sep='_', drop_first=True)
X_dict

COMMENT_ID_LZQPQhLyRh9-wNRtlZDM90f1k0BrdVdJyN_YsaSwfxc  \
0                                                    0        
1                                                    0        
2                                                    0        
3                                                    0        
4                                                    0        
5                                                    1        
6                                                    0        
7                                                    0        
8                                                    0        
9                                                    0        
10                                                   0        
11                                                   0        
12                                                   0        
13                                                   0        
14                                                   0        
15                                                   0        
16                                                   0        
17                                                   0        
18                                                   0        
19                                                   0        
20                                                   0        
21                                                   0        
22                                                   0        
23                                                   0        
24                                                   0        
25                                                   0        
26                                                   0        
27                                                   0        
28                                                   0        
29                                                   0        
..                                                 ...        
320                                                  0        
321                                                  0        
322                                                  0        
323                                                  0        
324                                                  0        
325                                                  0        
326                                                  0        
327                                                  0        
328                                                  0        
329                                                  0        
330                                                  0        
331                                                  0        
332                                                  0        
333                                                  0        
334                                                  0        
335                                                  0        
336                                                  0        
337                                                  0        
338                                                  0        
339                                                  0        
340                                                  0        
341                                                  0        
342                                                  0        
343                                                  0        
344                                                  0        
345                                                  0        
346                                                  0        
347                                                  0        
348                                                  0        
349                                                  0        

     COMMENT_ID_LZQPQhLyRh9EXArr4ZnVcDonSbvSMHKYOT24e_qR6fE  \
0                                  

In [133]:
ds = pd.read_csv('/data/UMG/ProDeGree/Grad I/ML/Chronic_Kidney_Disease/chronic_kidney_disease.csv')
data = ds.to_dict(orient='records')
X1 = ds.iloc[:,0:24]
y1 = ds.iloc[:,-1]

X_DV1 = DictVectorizer(sparse=False)

X_encoded1 = X_DV1.fit_transform(X1)

#support = SelectKBest(score_func=chi2, k=10)
#fit = support.fit(X_encoded1, y1)

features = fit.transform(X_encoded1)
#np.set_printoptions(precision=3) 

#print(features[0:5,:])

AttributeError: 'str' object has no attribute 'items'